#!/usr/bin/env bash

set -e

ARCH="x64"
if [[ $(uname -m) == "armv7l" ]]; then
  ARCH="arm"
elif [[ $(uname -m) == "aarch64" ]]; then
  ARCH="arm64"
fi

curl -s -L -o actions.tar.gz "https://github.com/actions/runner/releases/download/v2.280.2/actions-runner-linux-${ARCH}-2.280.2.tar.gz"
tar xf actions.tar.gz
rm -f actions.tar.gz
sudo ./bin/installdependencies.sh
